\hypertarget{classv8_1_1_try_catch}{}\section{v8\+:\+:Try\+Catch Class Reference}
\label{classv8_1_1_try_catch}\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}


{\ttfamily \#include $<$v8.\+h$>$}

\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\hyperlink{classv8_1_1_try_catch_ae3b6a2248b687b2cbc5271fcc2e40d66}{V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+E\+\_\+\+S\+O\+O\+N} (\char`\"{}Use isolate version\char`\"{}, Try\+Catch())
\item 
\hyperlink{classv8_1_1_try_catch_a623ce624491b383fae60c05d2aeefb1a}{Try\+Catch} (\hyperlink{classv8_1_1_isolate}{Isolate} $\ast$isolate)
\item 
\hyperlink{classv8_1_1_try_catch_a2c9ad4b40d17dd31c6dd020736b30679}{$\sim$\+Try\+Catch} ()
\item 
bool \hyperlink{classv8_1_1_try_catch_a48f704fbf2b82564b5d2a4ff596e4137}{Has\+Caught} () const 
\item 
bool \hyperlink{classv8_1_1_try_catch_a2ec467d4653d26c064d749cab98791cb}{Can\+Continue} () const 
\item 
bool \hyperlink{classv8_1_1_try_catch_a7e012477ac47db9480f85d55427987c7}{Has\+Terminated} () const 
\item 
\hyperlink{classv8_1_1_local}{Handle}$<$ \hyperlink{classv8_1_1_value}{Value} $>$ \hyperlink{classv8_1_1_try_catch_a4a7506617800bbc49c3c08bbfefb9c2d}{Re\+Throw} ()
\item 
\hyperlink{classv8_1_1_local}{Local}$<$ \hyperlink{classv8_1_1_value}{Value} $>$ \hyperlink{classv8_1_1_try_catch_a99c425f29b3355b4294cbe762377f99b}{Exception} () const 
\item 
\hyperlink{classv8_1_1_try_catch_ae8128ec2dae652a47c545d775c7778f7}{V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+E\+\_\+\+S\+O\+O\+N} (\char`\"{}Use maybe version.\char`\"{}, Local$<$ \hyperlink{classv8_1_1_value}{Value} $>$ \hyperlink{classv8_1_1_stack_trace}{Stack\+Trace}()) const 
\item 
\hypertarget{classv8_1_1_try_catch_a449fe4cdc063d234f2bea39e9297ba28}{}V8\+\_\+\+W\+A\+R\+N\+\_\+\+U\+N\+U\+S\+E\+D\+\_\+\+R\+E\+S\+U\+L\+T \hyperlink{classv8_1_1_maybe_local}{Maybe\+Local}$<$ \hyperlink{classv8_1_1_value}{Value} $>$ {\bfseries Stack\+Trace} (\hyperlink{classv8_1_1_local}{Local}$<$ \hyperlink{classv8_1_1_context}{Context} $>$ context) const \label{classv8_1_1_try_catch_a449fe4cdc063d234f2bea39e9297ba28}

\item 
\hyperlink{classv8_1_1_local}{Local}$<$ \hyperlink{classv8_1_1_message}{v8\+::\+Message} $>$ \hyperlink{classv8_1_1_try_catch_a2811e500fbb906ee505895a3d94fc66f}{Message} () const 
\item 
void \hyperlink{classv8_1_1_try_catch_a3aae8acab4c99b374b7d782763d4c8e1}{Reset} ()
\item 
void \hyperlink{classv8_1_1_try_catch_a032cd889d76bd596e2616df11ced8682}{Set\+Verbose} (bool value)
\item 
void \hyperlink{classv8_1_1_try_catch_a541b8fa6951bd5a439692c22d5c7b73c}{Set\+Capture\+Message} (bool value)
\end{DoxyCompactItemize}
\subsection*{Static Public Member Functions}
\begin{DoxyCompactItemize}
\item 
static void $\ast$ \hyperlink{classv8_1_1_try_catch_ac2e6359fa11a2aba609af82fb80cf07a}{J\+S\+Stack\+Comparable\+Address} (\hyperlink{classv8_1_1_try_catch}{v8\+::\+Try\+Catch} $\ast$handler)
\end{DoxyCompactItemize}
\subsection*{Friends}
\begin{DoxyCompactItemize}
\item 
\hypertarget{classv8_1_1_try_catch_acda8e558d20805fa72df899e935081aa}{}class {\bfseries v8\+::internal\+::\+Isolate}\label{classv8_1_1_try_catch_acda8e558d20805fa72df899e935081aa}

\end{DoxyCompactItemize}


\subsection{Detailed Description}
An external exception handler. 

\subsection{Constructor \& Destructor Documentation}
\hypertarget{classv8_1_1_try_catch_a623ce624491b383fae60c05d2aeefb1a}{}\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Try\+Catch@{Try\+Catch}}
\index{Try\+Catch@{Try\+Catch}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection[{Try\+Catch}]{\setlength{\rightskip}{0pt plus 5cm}v8\+::\+Try\+Catch\+::\+Try\+Catch (
\begin{DoxyParamCaption}
\item[{{\bf Isolate} $\ast$}]{isolate}
\end{DoxyParamCaption}
)}\label{classv8_1_1_try_catch_a623ce624491b383fae60c05d2aeefb1a}
Creates a new try/catch block and registers it with \hyperlink{namespacev8}{v8}. Note that all \hyperlink{classv8_1_1_try_catch}{Try\+Catch} blocks should be stack allocated because the memory location itself is compared against Java\+Script try/catch blocks. \hypertarget{classv8_1_1_try_catch_a2c9ad4b40d17dd31c6dd020736b30679}{}\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!````~Try\+Catch@{$\sim$\+Try\+Catch}}
\index{````~Try\+Catch@{$\sim$\+Try\+Catch}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection[{$\sim$\+Try\+Catch}]{\setlength{\rightskip}{0pt plus 5cm}v8\+::\+Try\+Catch\+::$\sim$\+Try\+Catch (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
)}\label{classv8_1_1_try_catch_a2c9ad4b40d17dd31c6dd020736b30679}
Unregisters and deletes this try/catch block. 

\subsection{Member Function Documentation}
\hypertarget{classv8_1_1_try_catch_a2ec467d4653d26c064d749cab98791cb}{}\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Can\+Continue@{Can\+Continue}}
\index{Can\+Continue@{Can\+Continue}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection[{Can\+Continue}]{\setlength{\rightskip}{0pt plus 5cm}bool v8\+::\+Try\+Catch\+::\+Can\+Continue (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
) const}\label{classv8_1_1_try_catch_a2ec467d4653d26c064d749cab98791cb}
For certain types of exceptions, it makes no sense to continue execution.

If Can\+Continue returns false, the correct action is to perform any C++ cleanup needed and then return. If Can\+Continue returns false and Has\+Terminated returns true, it is possible to call Cancel\+Terminate\+Execution in order to continue calling into the engine. \hypertarget{classv8_1_1_try_catch_a99c425f29b3355b4294cbe762377f99b}{}\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Exception@{Exception}}
\index{Exception@{Exception}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection[{Exception}]{\setlength{\rightskip}{0pt plus 5cm}{\bf Local}$<${\bf Value}$>$ v8\+::\+Try\+Catch\+::\+Exception (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
) const}\label{classv8_1_1_try_catch_a99c425f29b3355b4294cbe762377f99b}
Returns the exception caught by this try/catch block. If no exception has been caught an empty handle is returned.

The returned handle is valid until this \hyperlink{classv8_1_1_try_catch}{Try\+Catch} block has been destroyed. \hypertarget{classv8_1_1_try_catch_a48f704fbf2b82564b5d2a4ff596e4137}{}\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Has\+Caught@{Has\+Caught}}
\index{Has\+Caught@{Has\+Caught}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection[{Has\+Caught}]{\setlength{\rightskip}{0pt plus 5cm}bool v8\+::\+Try\+Catch\+::\+Has\+Caught (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
) const}\label{classv8_1_1_try_catch_a48f704fbf2b82564b5d2a4ff596e4137}
Returns true if an exception has been caught by this try/catch block. \hypertarget{classv8_1_1_try_catch_a7e012477ac47db9480f85d55427987c7}{}\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Has\+Terminated@{Has\+Terminated}}
\index{Has\+Terminated@{Has\+Terminated}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection[{Has\+Terminated}]{\setlength{\rightskip}{0pt plus 5cm}bool v8\+::\+Try\+Catch\+::\+Has\+Terminated (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
) const}\label{classv8_1_1_try_catch_a7e012477ac47db9480f85d55427987c7}
Returns true if an exception has been caught due to script execution being terminated.

There is no Java\+Script representation of an execution termination exception. Such exceptions are thrown when the Terminate\+Execution methods are called to terminate a long-\/running script.

If such an exception has been thrown, Has\+Terminated will return true, indicating that it is possible to call Cancel\+Terminate\+Execution in order to continue calling into the engine. \hypertarget{classv8_1_1_try_catch_ac2e6359fa11a2aba609af82fb80cf07a}{}\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!J\+S\+Stack\+Comparable\+Address@{J\+S\+Stack\+Comparable\+Address}}
\index{J\+S\+Stack\+Comparable\+Address@{J\+S\+Stack\+Comparable\+Address}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection[{J\+S\+Stack\+Comparable\+Address}]{\setlength{\rightskip}{0pt plus 5cm}static void$\ast$ v8\+::\+Try\+Catch\+::\+J\+S\+Stack\+Comparable\+Address (
\begin{DoxyParamCaption}
\item[{{\bf v8\+::\+Try\+Catch} $\ast$}]{handler}
\end{DoxyParamCaption}
)\hspace{0.3cm}{\ttfamily [inline]}, {\ttfamily [static]}}\label{classv8_1_1_try_catch_ac2e6359fa11a2aba609af82fb80cf07a}
There are cases when the raw address of C++ \hyperlink{classv8_1_1_try_catch}{Try\+Catch} object cannot be used for comparisons with addresses into the J\+S stack. The cases are\+: 1) A\+R\+M, A\+R\+M64 and M\+I\+P\+S simulators which have separate J\+S stack. 2) Address sanitizer allocates local C++ object in the heap when Use\+After\+Return mode is enabled. This method returns address that can be used for comparisons with addresses into the J\+S stack. When neither simulator nor A\+S\+A\+N\textquotesingle{}s Use\+After\+Return is enabled, then the address returned will be the address of the C++ try catch handler itself. \hypertarget{classv8_1_1_try_catch_a2811e500fbb906ee505895a3d94fc66f}{}\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Message@{Message}}
\index{Message@{Message}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection[{Message}]{\setlength{\rightskip}{0pt plus 5cm}{\bf Local}$<${\bf v8\+::\+Message}$>$ v8\+::\+Try\+Catch\+::\+Message (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
) const}\label{classv8_1_1_try_catch_a2811e500fbb906ee505895a3d94fc66f}
Returns the message associated with this exception. If there is no message associated an empty handle is returned.

The returned handle is valid until this \hyperlink{classv8_1_1_try_catch}{Try\+Catch} block has been destroyed. \hypertarget{classv8_1_1_try_catch_a3aae8acab4c99b374b7d782763d4c8e1}{}\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Reset@{Reset}}
\index{Reset@{Reset}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection[{Reset}]{\setlength{\rightskip}{0pt plus 5cm}void v8\+::\+Try\+Catch\+::\+Reset (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
)}\label{classv8_1_1_try_catch_a3aae8acab4c99b374b7d782763d4c8e1}
Clears any exceptions that may have been caught by this try/catch block. After this method has been called, \hyperlink{classv8_1_1_try_catch_a48f704fbf2b82564b5d2a4ff596e4137}{Has\+Caught()} will return false. Cancels the scheduled exception if it is caught and \hyperlink{classv8_1_1_try_catch_a4a7506617800bbc49c3c08bbfefb9c2d}{Re\+Throw()} is not called before.

It is not necessary to clear a try/catch block before using it again; if another exception is thrown the previously caught exception will just be overwritten. However, it is often a good idea since it makes it easier to determine which operation threw a given exception. \hypertarget{classv8_1_1_try_catch_a4a7506617800bbc49c3c08bbfefb9c2d}{}\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Re\+Throw@{Re\+Throw}}
\index{Re\+Throw@{Re\+Throw}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection[{Re\+Throw}]{\setlength{\rightskip}{0pt plus 5cm}{\bf Handle}$<${\bf Value}$>$ v8\+::\+Try\+Catch\+::\+Re\+Throw (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
)}\label{classv8_1_1_try_catch_a4a7506617800bbc49c3c08bbfefb9c2d}
Throws the exception caught by this \hyperlink{classv8_1_1_try_catch}{Try\+Catch} in a way that avoids it being caught again by this same \hyperlink{classv8_1_1_try_catch}{Try\+Catch}. As with Throw\+Exception it is illegal to execute any Java\+Script operations after calling Re\+Throw; the caller must return immediately to where the exception is caught. \hypertarget{classv8_1_1_try_catch_a541b8fa6951bd5a439692c22d5c7b73c}{}\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Set\+Capture\+Message@{Set\+Capture\+Message}}
\index{Set\+Capture\+Message@{Set\+Capture\+Message}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection[{Set\+Capture\+Message}]{\setlength{\rightskip}{0pt plus 5cm}void v8\+::\+Try\+Catch\+::\+Set\+Capture\+Message (
\begin{DoxyParamCaption}
\item[{bool}]{value}
\end{DoxyParamCaption}
)}\label{classv8_1_1_try_catch_a541b8fa6951bd5a439692c22d5c7b73c}
Set whether or not this \hyperlink{classv8_1_1_try_catch}{Try\+Catch} should capture a \hyperlink{classv8_1_1_message}{Message} object which holds source information about where the exception occurred. True by default. \hypertarget{classv8_1_1_try_catch_a032cd889d76bd596e2616df11ced8682}{}\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Set\+Verbose@{Set\+Verbose}}
\index{Set\+Verbose@{Set\+Verbose}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection[{Set\+Verbose}]{\setlength{\rightskip}{0pt plus 5cm}void v8\+::\+Try\+Catch\+::\+Set\+Verbose (
\begin{DoxyParamCaption}
\item[{bool}]{value}
\end{DoxyParamCaption}
)}\label{classv8_1_1_try_catch_a032cd889d76bd596e2616df11ced8682}
Set verbosity of the external exception handler.

By default, exceptions that are caught by an external exception handler are not reported. Call Set\+Verbose with true on an external exception handler to have exceptions caught by the handler reported as if they were not caught. \hypertarget{classv8_1_1_try_catch_ae3b6a2248b687b2cbc5271fcc2e40d66}{}\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+E\+\_\+\+S\+O\+O\+N@{V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+E\+\_\+\+S\+O\+O\+N}}
\index{V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+E\+\_\+\+S\+O\+O\+N@{V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+E\+\_\+\+S\+O\+O\+N}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection[{V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+E\+\_\+\+S\+O\+O\+N}]{\setlength{\rightskip}{0pt plus 5cm}v8\+::\+Try\+Catch\+::\+V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+E\+\_\+\+S\+O\+O\+N (
\begin{DoxyParamCaption}
\item[{\char`\"{}Use isolate version\char`\"{}}]{, }
\item[{{\bf Try\+Catch}()}]{}
\end{DoxyParamCaption}
)}\label{classv8_1_1_try_catch_ae3b6a2248b687b2cbc5271fcc2e40d66}
Creates a new try/catch block and registers it with \hyperlink{namespacev8}{v8}. Note that all \hyperlink{classv8_1_1_try_catch}{Try\+Catch} blocks should be stack allocated because the memory location itself is compared against Java\+Script try/catch blocks. \hypertarget{classv8_1_1_try_catch_ae8128ec2dae652a47c545d775c7778f7}{}\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+E\+\_\+\+S\+O\+O\+N@{V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+E\+\_\+\+S\+O\+O\+N}}
\index{V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+E\+\_\+\+S\+O\+O\+N@{V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+E\+\_\+\+S\+O\+O\+N}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection[{V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+E\+\_\+\+S\+O\+O\+N}]{\setlength{\rightskip}{0pt plus 5cm}v8\+::\+Try\+Catch\+::\+V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+E\+\_\+\+S\+O\+O\+N (
\begin{DoxyParamCaption}
\item[{\char`\"{}Use maybe version.\char`\"{}}]{, }
\item[{{\bf Local}$<$ {\bf Value} $>$ }]{Stack\+Trace()}
\end{DoxyParamCaption}
) const}\label{classv8_1_1_try_catch_ae8128ec2dae652a47c545d775c7778f7}
Returns the .stack property of the thrown object. If no .stack property is present an empty handle is returned. 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
deps/v8/include/v8.\+h\end{DoxyCompactItemize}
